// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCas9iWc8N1e13ODbn3RHFoa-QNlF2o5dY',
    appId: '1:759517838065:web:3ede0dd01588279c4d8750',
    messagingSenderId: '759517838065',
    projectId: 'shopwithme-9ce85',
    authDomain: 'shopwithme-9ce85.firebaseapp.com',
    storageBucket: 'shopwithme-9ce85.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC1GOg7VusFFl2LSYhqDV5PfjCIAwz_0k',
    appId: '1:759517838065:android:30303f95a6ddefd94d8750',
    messagingSenderId: '759517838065',
    projectId: 'shopwithme-9ce85',
    storageBucket: 'shopwithme-9ce85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbyIknX2dTaC65DXBpeBRkHGvLTencSgM',
    appId: '1:759517838065:ios:02f40261f466cbba4d8750',
    messagingSenderId: '759517838065',
    projectId: 'shopwithme-9ce85',
    storageBucket: 'shopwithme-9ce85.appspot.com',
    iosBundleId: 'com.example.idea1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbyIknX2dTaC65DXBpeBRkHGvLTencSgM',
    appId: '1:759517838065:ios:cdecf54bc96bd1e94d8750',
    messagingSenderId: '759517838065',
    projectId: 'shopwithme-9ce85',
    storageBucket: 'shopwithme-9ce85.appspot.com',
    iosBundleId: 'com.example.idea1.RunnerTests',
  );
}
